CLASS bp_bookingsupplement_u DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF i_travel_u .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS bp_bookingsupplement_u IMPLEMENTATION.
ENDCLASS.
