"! @testing CL_I_TRAVEL_TUM
"! @testing CL_C_TRAVEL_TUM
"! @testing CL_FLIGHT_LEGACY
"! @testing FUGR:FLIGHT_TRAVEL_API
CLASS ltc DEFINITION FINAL INHERITING FROM tc_flight_travel_api FOR TESTING RISK LEVEL HARMLESS DURATION MEDIUM.
ENDCLASS.
